# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_note_docfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='docfile',
            field=models.FileField(blank=True, default='', upload_to='documents/%Y/%m/%d'),
        ),
    ]
