# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_auto_20161125_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='author',
        ),
        migrations.RemoveField(
            model_name='note',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='note',
            name='description',
        ),
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
        migrations.AlterField(
            model_name='note',
            name='docfile',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
